name: Android CI

on: 
  pull_request:
    branches:
    - develop_copy
    
jobs:
  Debug:
    name: Run Unit Tests(GE)
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Execute Unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest

    # Generate report
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "**/test-results/testDebugUnitTest/*.xml"
        if: always()
        
    - name: Upload test summary
      uses: actions/upload-artifact@v3
      with:
        name: test-summary
        path: test-summary.md
      if: always()

