name: Android CI

on: 
  pull_request:
    branches:
    - develop_copy
    
jobs:
  Debug:
    name: Run Unit Tests(GE)
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Execute Unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest

    # Generate report
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "**/testDebugUnitTest/*.xml"
      if: always()
